# Generated by Django 2.0 on 2020-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('Text', models.TextField()),
            ],
        ),
    ]
